name: Bug Report
description: File a bug report to help us improve opentelemetry-proto-go
title: "[Bug]: "
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true
  
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: What steps can we follow to reproduce this issue?
      placeholder: |
        1. 
        2. 
        3. 
    validations:
      required: true
  
  - type: textarea
    id: expected
    attributes:
      label: Expected Result
      description: What did you expect to happen?
    validations:
      required: true
  
  - type: textarea
    id: actual
    attributes:
      label: Actual Result
      description: What actually happened?
    validations:
      required: true
  
  - type: textarea
    id: otel-version
    attributes:
      label: OpenTelemetry Proto Go Version
      description: What version of opentelemetry-proto-go are you using?
      placeholder: e.g., v1.0.0
    validations:
      required: true
  
  - type: textarea
    id: go-version
    attributes:
      label: Go Version
      description: What version of Go are you using?
      placeholder: e.g., go1.21.5
    validations:
      required: true
  
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        Please provide details about your environment:
        - OS (e.g., Linux, Windows, macOS)
        - Architecture (e.g., amd64, arm64)
      placeholder: |
        - OS: 
        - Architecture: 
    validations:
      required: true
  
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!
        
        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  
  - type: dropdown
    attributes:
      label: Tip
      description: This element is static, used to render a helpful sub-heading for end-users and community members to help prioritize issues. Please leave as is.
      options:
        - <sub>[React](https://github.blog/news-insights/product-news/add-reactions-to-pull-requests-issues-and-comments/) with 👍 to help prioritize this issue. Please use comments to provide useful context, avoiding `+1` or `me too`, to help us triage it. Learn more [here](https://opentelemetry.io/community/end-user/issue-participation/).</sub>
      default: 0